import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from '../../components/sidebar';
import React from "react";
import { NextIntlClientProvider, useMessages } from "next-intl";
import "./globals.css"

const inter = Inter({ subsets: ["latin"] });

type Props = {
  children: React.ReactNode;
  params: {
    locale: "en" | "tr"
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<Props> = ({
  children,
  params: { locale },
}) => {
  const messages = useMessages()
  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <body className={inter.className}>
          <div className="flex h-screen w-full">
            <Sidebar />
            <div className="flex flex-col w-full h-full ml-64 p-4">
              {children}
            </div>
          </div>
        </body>
      </NextIntlClientProvider>

    </html>
  );
}

export default RootLayout
